### ISSUE TITLE
Support for multiple states

### ISSUE THREAD

**Issue by janbaer** [mikaelbr/gulp-gitmodified#2]
It seems that it's not possible to set more then one status. It would be helpful to be able to set AM for example to return all added and modified files. Thanks!

**Comment by mikaelbr** [comment]
Hi. Good idea! PRs are very welcome, or I'll have to look at this a bit later, but it should be fairly simple to implement. Especially when using single letters (A and M)

**Comment by oluckyman** [comment]
Hey Mikael did something on this?
If no, I gonna do this. I’m thinking to use `|` as delimiter. In this case you can just pass string `"A|M|??"` to RegExp and it will work.

**Comment by mikaelbr** [comment]
@oluckyman I haven't gotten the chance to look at this yet. Feel free to look into this :+1:

**Comment by alistairjcbrown** [comment]
I just ran into this trying to pull in all files which have been either `modified`, `added` or are `untracked`, so a big +1 from me @oluckyman

**Comment by alistairjcbrown** [comment]
I had a few hours free tonight - PR for multiple modes to be provided: https://github.com/mikaelbr/gulp-gitmodified/pull/3

**Comment by oluckyman** [comment]
Just grabbed a cup of tea and got ready to hack on this issue and here you are @alistairjcbrown! 🚀
Thanks a lot!👏
Your move @mikaelbr :) looking forward to updated version on npm :)

**Comment by mikaelbr** [comment]
Updated the package where this is fixed! Thanks to everyone involved!

```shell
➜  gulp-gitmodified git:(master) npm publish
+ gulp-gitmodified@1.0.0
```

**Comment by alistairjcbrown** [comment]
LGTM - `gitmodified(['modified', 'added'])` shows up both modified and added files in my linting task

**Comment by mikaelbr** [comment]
Perfect. I'm closing this.
